### ISSUE TITLE
Error messages aren't particularly useful

### ISSUE THREAD

**Issue by HistoireDeBabar** [fac/serverless-tools#36]
There's a few error messages that aren't particularly useful. 

In the following case it would be nice to have a bit more of an idea what failed:
e.g. 
```zsh
dev serverless-tools deploy update -f -x
    ❌ Failed to update
```
 
 
 On the other hand, when errors aren't handled we get a full stack trace - in this case, it would be nicer if we had less information, and it was more clearly presented:
 ```
 Traceback (most recent call last):
        13: from /Users/paulbarber/.gem/ruby/2.7.0/bin/serverless-tools:23:in `<main>'
        12: from /Users/paulbarber/.gem/ruby/2.7.0/bin/serverless-tools:23:in `load'
        11: from /Users/paulbarber/.gem/ruby/2.7.0/gems/serverless-tools-0.6.0/bin/serverless-tools:5:in `<top (required)>'
        10: from /Users/paulbarber/.gem/ruby/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
         9: from /Users/paulbarber/.gem/ruby/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
         8: from /Users/paulbarber/.gem/ruby/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
         7: from /Users/paulbarber/.gem/ruby/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
         6: from /Users/paulbarber/.gem/ruby/2.7.0/gems/serverless-tools-0.6.0/lib/serverless-tools/cli.rb:20:in `deploy'
         5: from /Users/paulbarber/.gem/ruby/2.7.0/gems/serverless-tools-0.6.0/lib/serverless-tools/deployer.rb:11:in `deploy'
         4: from /Users/paulbarber/.gem/ruby/2.7.0/gems/serverless-tools-0.6.0/lib/serverless-tools/deployer.rb:11:in `new'
         3: from /Users/paulbarber/.gem/ruby/2.7.0/gems/serverless-tools-0.6.0/lib/serverless-tools/deployer/yaml_config_loader.rb:12:in `initialize'
         2: from /Users/paulbarber/.rubies/ruby-2.7.0/lib/ruby/2.7.0/psych.rb:577:in `load_file'
         1: from /Users/paulbarber/.rubies/ruby-2.7.0/lib/ruby/2.7.0/psych.rb:577:in `open'
/Users/paulbarber/.rubies/ruby-2.7.0/lib/ruby/2.7.0/psych.rb:577:in `initialize': No such file or directory @ rb_sysopen - functions.yml (Errno::ENOENT)
        11: from /Users/paulbarber/.gem/ruby/2.7.0/bin/serverless-tools:23:in `<main>'
        10: from /Users/paulbarber/.gem/ruby/2.7.0/bin/serverless-tools:23:in `load'
         9: from /Users/paulbarber/.gem/ruby/2.7.0/gems/serverless-tools-0.6.0/bin/serverless-tools:5:in `<top (required)>'
         8: from /Users/paulbarber/.gem/ruby/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
         7: from /Users/paulbarber/.gem/ruby/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
         6: from /Users/paulbarber/.gem/ruby/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
         5: from /Users/paulbarber/.gem/ruby/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
         4: from /Users/paulbarber/.gem/ruby/2.7.0/gems/serverless-tools-0.6.0/lib/serverless-tools/cli.rb:20:in `deploy'
         3: from /Users/paulbarber/.gem/ruby/2.7.0/gems/serverless-tools-0.6.0/lib/serverless-tools/deployer.rb:11:in `deploy'
         2: from /Users/paulbarber/.gem/ruby/2.7.0/gems/serverless-tools-0.6.0/lib/serverless-tools/deployer.rb:11:in `new'
         1: from /Users/paulbarber/.gem/ruby/2.7.0/gems/serverless-tools-0.6.0/lib/serverless-tools/deployer/yaml_config_loader.rb:11:in `initialize'
/Users/paulbarber/.gem/ruby/2.7.0/gems/serverless-tools-0.6.0/lib/serverless-tools/deployer/yaml_config_loader.rb:16:in `rescue in initialize': Could not find config file 'functions.yml' (ServerlessTools::Deployer::ConfigFileNotFound)
```

**Comment by dancorne** [comment]
I'd vote for stacktraces for anything unexpected, exceptions can be caught for known issues but still want to fall back to the full exception -- it's a tool for developers after all. Quite a lot of errors I hit were swallowed [here](https://github.com/fac/serverless-tools/blob/main/lib/serverless-tools/deployer/function_deployer.rb#L50) and I ended up adding a `raise` and/or referencing the error message from Cloudtrail in Humio.

**Comment by HistoireDeBabar** [comment]
We could add a verbose option to show full stack traces.

**Comment by HistoireDeBabar** [comment]
Closing this as the latest error handling partly handles this in the sense that is is consistent and more in depth than previous (i.e. you receive the stack trace). At the moment making the errors prettier in some contexts is not required.
